// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title  Verify — Basescan contract verification helper
 * @notice Run this after a successful broadcast to verify all contracts
 *         on Basescan. Requires BASESCAN_API_KEY in .env.
 *
 *         Usage (after mainnet deploy):
 *           # 1. Set addresses in .env after deployment
 *           # 2. Run:
 *           forge verify-contract $INKD_TOKEN_ADDRESS \
 *             src/InkdToken.sol:InkdToken \
 *             --chain base \
 *             --etherscan-api-key $BASESCAN_API_KEY \
 *             --watch
 *
 *           forge verify-contract $INKD_TREASURY_IMPL \
 *             src/InkdTreasury.sol:InkdTreasury \
 *             --chain base \
 *             --etherscan-api-key $BASESCAN_API_KEY \
 *             --watch
 *
 *           forge verify-contract $INKD_REGISTRY_IMPL \
 *             src/InkdRegistry.sol:InkdRegistry \
 *             --chain base \
 *             --etherscan-api-key $BASESCAN_API_KEY \
 *             --watch
 *
 *         Note: Proxies are verified automatically when using --verify in Deploy.s.sol
 *
 *         Alternatively, run: bash script/verify.sh (generated by post-deploy checklist)
 */

import {Script, console} from "forge-std/Script.sol";

contract Verify is Script {
    function run() external view {
        address token    = vm.envAddress("INKD_TOKEN_ADDRESS");
        address tImpl    = vm.envAddress("INKD_TREASURY_IMPL");
        address tProxy   = vm.envAddress("INKD_TREASURY_PROXY");
        address rImpl    = vm.envAddress("INKD_REGISTRY_IMPL");
        address rProxy   = vm.envAddress("INKD_REGISTRY_PROXY");
        string memory apiKey = vm.envString("BASESCAN_API_KEY");

        console.log("========================================");
        console.log("  Inkd Protocol — Verification Commands");
        console.log("========================================");
        console.log("");
        console.log("Run the following to verify all contracts:");
        console.log("");
        console.log("# 1. InkdToken");
        console.log(string.concat(
            "forge verify-contract ", vm.toString(token),
            " src/InkdToken.sol:InkdToken",
            " --chain base",
            " --etherscan-api-key ", apiKey,
            " --watch"
        ));
        console.log("");
        console.log("# 2. InkdTreasury (implementation)");
        console.log(string.concat(
            "forge verify-contract ", vm.toString(tImpl),
            " src/InkdTreasury.sol:InkdTreasury",
            " --chain base",
            " --etherscan-api-key ", apiKey,
            " --watch"
        ));
        console.log("");
        console.log("# 3. InkdRegistry (implementation)");
        console.log(string.concat(
            "forge verify-contract ", vm.toString(rImpl),
            " src/InkdRegistry.sol:InkdRegistry",
            " --chain base",
            " --etherscan-api-key ", apiKey,
            " --watch"
        ));
        console.log("");
        console.log("Proxy addresses (for Basescan UI only):");
        console.log("  InkdTreasury Proxy:", tProxy);
        console.log("  InkdRegistry Proxy:", rProxy);
        console.log("");
        console.log("After verification, mark verified on Basescan:");
        console.log("  https://basescan.org/address/", vm.toString(token), "#code");
        console.log("  https://basescan.org/address/", vm.toString(tProxy), "#code");
        console.log("  https://basescan.org/address/", vm.toString(rProxy), "#code");
    }
}
